<?php View::content() ?>
<?php if (isset($materias_inscritas)): ?>
<h2>Hola <b><?php echo ucfirst(Auth::get("apellidos"))." ".ucfirst(Auth::get("nombres")) ?></b></h2>
	
	<?php if (empty($materias_inscritas)): ?>
		<?php Flash::info("No hay evaluaciones asignadas") ?>
	<?php endif ?>
	<table class="table">
	<?php $i = 0 ?>
	
		<?php foreach ($materias_inscritas as $key => $value): ?>
			<thead>
				<th><center>Asignatura</center></th>
				<?php foreach ($evaluaciones[$i] as $key1 => $value1): ?>
					<th>
					<center>
						<?php echo $value1->unidad ?><br>
						<?php echo $value1->tipoevaluacion ?><br>
						<?php echo $value1->fecha ?><br>
						<?php echo str_replace("%", "", $value1->porcentaje)."%" ?><br>
						</center>
					</th>
				<?php endforeach ?>
				<th>Promedio</th>
			</thead>
			<tr>
				<td><center>
					<?php echo $cursos[$i][0]->asignatura ?>
					<?php $suma_promedio = 0; ?>
					<?php foreach ($evaluaciones[$i] as $key2 => $value2): ?>
					<?php $alumnoeva = $alumnoevaluacion->find("columns: alumnoevaluacion.id,incripcionalumnoasignatura_id,profesorevaluacion_id,ponderacion,porcentaje","conditions: incripcionalumnoasignatura_id = '{$value->id}'  and profesorevaluacion_id =  '{$value2->id}' ","join: inner join profesorevaluacion on profesorevaluacion.id = alumnoevaluacion.profesorevaluacion_id")?>
						<td>
							<center><?php echo " (".$alumnoeva[0]->ponderacion.")  ".$alumnoeva[0]->ponderacion*$alumnoeva[0]->porcentaje/100 ?>
							<?php $suma_promedio += $alumnoeva[0]->ponderacion*$alumnoeva[0]->porcentaje/100 ?>
							</center>
						</td>
					<?php endforeach ?>
					<td><?php echo round($suma_promedio) ?></td>
				</center></td>
				
			</tr>
			<?php $i++; ?>
		<?php endforeach ?>
	</table>
<?php endif ?>


<?php if(isset($docente) and isset($asignaturas)): ?>
	<?php echo Tag::css("mios"); ?>
	<div class="alert bg-info">
		<div class="pull-left">
			<?php echo Html::img("salon.png","icono de secciones","width='100px'") ?>
		</div>
		<div class="pull-left" >
			<h2 class="titulo_de_imagen"><?php echo $titulo ?></h2>
		</div>
		<div class="clearfix"></div>
		
		<div class="clearfix"></div>
		<br>
		<div class="pull-right">
		<div class="clearfix"></div>

	</div>
	
	<ul class="list-group">
	<?php foreach ($asignaturas as $key => $value): ?>
		<li class="list-group-item">
			<?php echo Html::link("perfil/programarevaluaciones/{$value->profesorasignatura_id}","<span class='glyphicon glyphicon-ok'></span> Semestre ".$value->numero." : Sección: ".$value->seccion." - ".$value->codigo." - ".$value->asignatura,"class='btn btn-default'") ?>
		</li>
	<?php endforeach ?>
	</ul>
<?php View::content() ?>
<?php endif; ?>