<?php View::content() ?>

<?php if (isset($informacion_alumno)): ?>
	<?php if (empty($informacion_alumno)): ?>
		<?php Flash::info("No hay evaluaciones asignadas") ?>
	<?php endif ?>
	<table class="table datatable">
		<thead>
			<th>Fecha</th>
			<th>Estrategia - Descripcion</th>
			<th>Unidad</th>
			<th>Asignatura</th>
			<th>Semestre</th>
			<th>Seccion</th>
			<th>Profesor</th>
			<th>Ponderación</th>
			<th>Terminado</th>
		</thead>
		<?php foreach ($informacion_alumno as $key => $value): ?>
			<tr>
				<td><?php echo $value->fecha ?></td>
				<td><?php echo ucfirst($value->estrategia)." - ".ucfirst($value->descripcion) ?></td>
				<td><?php echo ucfirst($value->unidad) ?></td>
				<td><?php echo ucfirst($value->asignatura) ?></td>
				<td><?php echo ucfirst($value->numero) ?></td>
				<td><?php echo ucfirst($value->seccion) ?></td>
				<td><?php echo ucfirst($value->apellidos)." ".ucfirst($value->nombres) ?></td>
				<td><?php echo $value->ponderacion ?></td>
				<td><?php echo $value->terminado ? "Si" : "No" ?></td>
			</tr>
		<?php endforeach ?>
	</table>
<?php endif ?>


<?php if(isset($docente) and isset($asignaturas)): ?>
	<?php echo Tag::css("mios"); ?>
	<div class="alert bg-info">
		<div class="pull-left">
			<?php echo Html::img("salon.png","icono de secciones","width='100px'") ?>
		</div>
		<div class="pull-left" >
			<h2 class="titulo_de_imagen"><?php echo $titulo ?></h2>
		</div>
		<div class="clearfix"></div>
		
		<div class="clearfix"></div>
		<br>
		<div class="pull-right">
		<div class="clearfix"></div>

	</div>
	
	<ul class="list-group">
	<?php foreach ($asignaturas as $key => $value): ?>
		<li class="list-group-item">
			<?php echo Html::link("perfil/programarevaluaciones/{$value->profesorasignatura_id}","<span class='glyphicon glyphicon-ok'></span> Semestre ".$value->numero." : Sección: ".$value->seccion." - ".$value->codigo." - ".$value->asignatura,"class='btn btn-default'") ?>
		</li>
	<?php endforeach ?>
	</ul>
<?php View::content() ?>
<?php endif; ?>