<?php View::content() ?>

<?php echo Form::open("","POST","class='form-inline'") ?>
	<div class="form-group">
		<label>Unidad</label>
		<?php echo Form::hidden("profesorevaluacion.profesorasignatura_id",null,$asignatura[0]->profesorasignatura_id) ?>
		<?php echo Form::text("profesorevaluacion.unidad","class='form-control'") ?>
	</div>
	<div class="form-group">
		<label>Tipo de evaluación</label>
		<?php echo Form::text("profesorevaluacion.tipoevaluacion","class='form-control'") ?>
	</div>
	<div class="form-group">
		<label>Porcentaje</label>
		<?php echo Form::text("profesorevaluacion.porcentaje","class='form-control'") ?>
	</div>
	<div class="form-group">
		<label>Fecha</label>
		<?php echo Form::text("profesorevaluacion.fecha","class='form-control datepicker'") ?>
	</div>
	<?php echo Form::submit("Programar","class='btn btn-default'") ?>
<?php echo Form::close() ?>
<hr>
<table class="table datatable">
	<thead>
		<th>Unidad</th>
		<th>Tipo de Evaluación</th>
		<th>Porcentaje</th>
		<th>Fecha</th>
		<th></th>
	</thead>
	<?php foreach ($evaluaciones as $key => $value): ?>
		<tr>
			<td><?php echo $value->unidad ?></td>
			<td><?php echo $value->tipoevaluacion ?></td>
			<td><?php echo $value->porcentaje ?></td>
			<td><?php echo $value->fecha ?></td>
			<!--profesorevaluacion_id / profesorasignatura_id-->
			<td><?php echo Html::link("calificar/grupo/{$value->id}/{$value->profesorasignatura_id}","Calificar","class='btn btn-default'") ?></td>
		</tr>
	<?php endforeach ?>
</table>

<table class="table datatable">
	<thead>
		<?php $columnas = 1; ?>
		<th>Apellidos y Nombres</th>

		<?php foreach ($evaluaciones as $key => $value): ?>
			<th>
				<center><?php echo ucfirst($value->unidad) ?></center>
				<center><?php echo ucfirst($value->tipoevaluacion) ?></center>
				<center><?php echo str_replace("%", "", $value->porcentaje)."%" ?> - (<?php echo $value->fecha ?>)</center>
			</th>
			<?php $columnas++; ?>
		<?php endforeach ?>
		<th>Promedio</th>
	</thead>
	<?php foreach ($notasalumnos as $key => $value): ?>
			<tr>
				<td><?php echo ucfirst($value->apellidos." ".$value->nombres) ?></td>
				<?php $r = $notasalumnos[0]->getNotasAsignaturaConAlumnosByProfesorAsignaturaIdAndAlumnoId($profesorasignatura_id,null,$value->id) ?>
				<?php $suma_promedio = 0; ?>
				<?php $suma_porcentaje = 0; ?>
				<?php foreach ($r as $key1 => $value1): ?>
					<td><center><?php echo $value1->ponderacion."/20" ?></center></td>
					<?php $porcentaje = $value1->ponderacion * $value1->porcentaje / 20  ?>
					<?php $suma_promedio+=$value1->ponderacion; ?>
					<?php $suma_porcentaje+=$porcentaje ?>
				<?php endforeach ?>
				<td><center><?php echo $suma_porcentaje."/100%" ?></center></td>
			</tr>
		<?php endforeach ?>
</table>

