<ul class="nav nav-pills">
	<?php $controlador = Router::get("controller") ?>
	<?php if ($controlador == "perfil"): ?>
  		<li role="presentation" class='active'><a href="#">Perfil</a></li>
	<?php else: ?>
		<li role="presentation"><a href="#">Perfil</a></li>
	<?php endif ?>
	<?php if ($controlador == "profesor"): ?>
 		<li role="presentation" class='active'><?php echo Html::link("profesor/","Profesores") ?></li>
  	<?php else: ?>
		<li role="presentation"><?php echo Html::link("profesor/","Profesores") ?></li>
  	<?php endif ?>
  	<?php if ($controlador == "alumno"): ?>
  		<li role="presentation" class='active'><?php echo Html::link("alumno/","Alumnos") ?></li>
  	<?php else: ?>
  		<li role="presentation"><?php echo Html::link("alumno/","Alumnos") ?></li>
  	<?php endif ?>
  	<?php if ($controlador == "asignatura"): ?>
  		<li role="presentation" class='active'><?php echo Html::link("asignatura/","Asignaturas") ?></li>
  	<?php else: ?>
  		<li role="presentation"><?php echo Html::link("asignatura/","Asignaturas") ?></li>
  	<?php endif ?>
</ul>