<?php echo Tag::css("mios"); ?>

<div class="alert bg-info">
	<div class="pull-left">
		<?php echo Html::img("materias.png","icono de materias","width='100px'") ?>
	</div>
	<div class="pull-left" >
		<h2 class="titulo_de_imagen"><?php echo $titulo ?></h2>
	</div>
	<div class="clearfix"></div>
	<div class="pull-right">
		<form class="form-inline" method="post">
		  <div class="form-group">
		    <input type="text" class="form-control input-sm" id="materia" placeholder="Buscar Materias">
		  </div>
		  <button type="submit" class="btn btn-default btn-sm">Buscar</button>
		</form>
	</div>
	<div class="clearfix"></div>
	<br>
	<div class="pull-right">
		<?php echo Html::link("materia/nueva","<span class=\"glyphicon glyphicon-plus\" aria-hidden=\"true\"></span>  Ingresar nueva Materia","class='btn btn-default btn-sm'") ?>
	</div>
	<div class="clearfix"></div>

</div>
