
<?php View::content() ?>

<?php echo Form::open("","POST","class='form-inline'") ?>
	<div class="form-group">
		<label>Descripción</label>
		<?php echo Form::hidden("asistencia.profesorasignatura_id",null,$profesorasignatura_id) ?>
		<?php echo Form::text("asistencia.descripcion","class='form-control'") ?>
	</div>
	<div class="form-group">
		<label>Fecha</label>
		<?php echo Form::text("asistencia.fecha","class='form-control datepicker'") ?>
	</div>
	<?php echo Form::submit("Guardar","class='btn btn-default'") ?>
<?php echo Form::close() ?>
<hr>
<table class="table datatable">
	<thead>
		<th>Descripción</th>
		<th>Fecha</th>
		<th></th>
	</thead>
	<?php foreach ($asistencia as $key => $value): ?>
		<tr>
			<td><?php echo $value->descripcion ?></td>
			<td><?php echo $value->fecha ?></td>
			<!--profesorevaluacion_id / profesorasignatura_id-->
			<td>

				<?php echo Html::link("asistencia/agregar_asistencia/$profesor_id/$profesorasignatura_id/{$value->id}","Agregar Asistencia","class='btn btn-default'") ?>
	
			</td>
		</tr>
	<?php endforeach ?>
</table>

<table class="table datatable">
	<thead>
		<?php $columnas = 0; ?>
		<th>Alumno</th>

		<?php foreach ($asistencia as $key => $value): ?>
			<th>
				<center><?php echo ucfirst($value->descripcion) ?></center>
			</th>
			<?php $columnas++; ?>
		<?php endforeach ?>
		<th>Total Asistencia</th>
		<th>Total Inasistencia</th>
		<th>% Inasistencia</th>
	</thead>
	<?php foreach ($asistencia_alumnos as $key => $value): ?>
		<?php $asistio = 0 ?>
		<?php $inasistencia = 0 ?>
		<?php $numero_asistencias = 0 ?>
			<tr>
				<td>
					<?php echo ucfirst($value->apellidos)." ".ucfirst($value->nombres)?>
				</td>
				<?php foreach ($asistencia as $key2 => $value2): ?>
					<?php $numero_asistencias++ ?>
					
						<?php $q = $asistencia[0]->getAsistenciaByAsistenciaIdYAlumnoId($value2->id,$value->alumno_id) ?>
						<td>
						<?php if ($q[0]->asistio): ?>
								<?php $asistio++ ?>
								Asistió
							<?php else: ?>
								No Asistió
								<?php $inasistencia++ ?>
						<?php endif ?>
						</td>
					
				<?php endforeach ?>
			
				
				
		
			<td><?php echo $asistio ?></td>
			<td><?php echo $inasistencia ?></td>
			<td><?php echo number_format(($inasistencia*100)/$columnas,2) ?>%</td>
		</tr>
		<?php endforeach ?>
</table>

<?php echo Html::link("perfil/programarevaluaciones/".$profesorasignatura_id,"Volver","class='btn btn-default'") ?>