  	<?php echo Form::open() ?>
 
        <h4 class="modal-title" id="myModalLabel">Formulario de evaluacion</h4>


      	<div class="row">
      		<div class="col-md-3">
      			<div class="form-group">
            <?php echo Form::hidden("alumnoasignatura.id") ?>
      				<label for="">Semestre</label>
      				<?php echo Form::dbselect("alumnoasignatura.semestre_id","numero",array("semestre","find"),"Semestre","class='form-control' required") ?>
      			</div>
      		</div>
  			<div class="col-md-2">
  				<div class="form-group">
      				<label for="">Sección</label>
      				<?php echo Form::select("alumnoasignatura.seccion_id",$secciones,"class='form-control' required") ?>
      			</div>
      			
  			</div>
	      	<div class="col-md-7">
  				<div class="form-group">
      				<label for="">Asignatura</label>
      				<?php echo Form::dbselect("alumnoasignatura.asignatura_id","asignatura",null,"Asignatura","class='form-control' required") ?>
      			</div>
  			</div>
      	</div>
      	<div class="row">
      		
      		<div class="col-md-6">
      			<div class="form-group">
      				<label for="">Estrategia</label>
				      <?php echo Form::text("alumnoasignatura.estrategia","class='form-control' required") ?>
      			</div>
				    <div class="form-group">
      				<label for="">Alumno</label>
      				<?php echo Form::dbselect("alumnoasignatura.alumno_id","alum",array("alumno","getAlumnos"),"Alumno","class='form-control' required") ?>
      			</div>

      			<div class="form-group">
      				<label for="">Unidad</label>
      				<?php echo Form::text("alumnoasignatura.unidad","class='form-control' required") ?>
      			</div>
      			<div class="form-group">
      				<label for="">Ponderación</label>
      				<?php echo Form::text("alumnoasignatura.ponderacion","class='form-control'") ?>
      			</div>
            
      		</div>
      		<div class="col-md-6">
	      		<div class="form-group">
	      			<label for="">Descripción</label>
					<?php echo Form::text("alumnoasignatura.descripcion","class='form-control' required") ?>
	      		</div>
				    <div class="form-group">
      				<label for="">Profesor</label>
      				<?php echo Form::dbselect("alumnoasignatura.profesor_id","prof",array("profesor","getProfesores"),"Profesor","class='form-control' required") ?>
      			</div>
      			<div class="form-group">
      				<label for="">Fecha</label>
      				<?php echo Form::text("alumnoasignatura.fecha","class='form-control datepicker' required") ?>
      			</div>
            <div class="form-group">
              <label for="">Terminado</label>
              <br>
              SI
              <?php echo Form::radio("alumnoasignatura.terminado","1") ?>
              No
              <?php echo Form::radio("alumnoasignatura.terminado","0") ?>
            </div>
      		</div>
        </div>
 
        <?php echo Html::link("evaluacion/","Regresar a lista de evaluaciones","class='btn btn-default'") ?>
        <button type="submit" class="btn btn-primary">Actualizar</button>

    </div>
    <?php echo Form::close() ?>

<script type="text/javascript">


    $(document).ready(function(){
   
    $("#alumnoasignatura_semestre_id").on("change",function(){
      var id = $(this).val();
      $("#cargando").css("display","block");
      $.ajax({
        url:"../../seccion/obtener_secciones_por_semestre/?id="+id,
        type:"get",
        dataType:"json",
        async:false,
        success:function(r){
          options = '';
          for (var i = 0; i < r.length; i++) {
            options+= "<option value='"+r[i].id+"'>"+r[i].seccion+"</option>";
          };
          $("#alumnoasignatura_seccion_id").html(options);
          $("#cargando").css("display","none");
          //console.log(r);
        }

      })
      $.ajax({
        url:"../../seccion/obtener_asignaturas_por_semestre_alumno/?id="+id,
        type:"get",
        dataType:"json",
        async:false,
        success:function(r){
          console.log(r)
          options = '';
          if (!r.length) {
            alert("No existen materias registradas para este semestre");
          };
          for (var i = 0; i < r.length; i++) {
            options+= "<option value='"+r[i].id+"'>"+r[i].codigo+"-"+r[i].asignatura+"</option>";
          };
          $("#alumnoasignatura_asignatura_id").html(options);
          $("#cargando").css("display","none");
          //console.log(r);
        }

      })
    })
    $("#alumnoasignatura_asignatura_id,#alumnoasignatura_seccion_id").on("change",function(){
        var id_asig = $(this).val();
        var id_semestre = $("#alumnoasignatura_semestre_id").val();
        var id_seccion = $("#alumnoasignatura_seccion_id").val();
        $.ajax({
          url:"../../seccion/obtener_profesor_de_asignatura/?semestre_id="+id_semestre+"&seccion_id="+id_seccion+"&id="+id_asig,
          type:"get",
          dataType:"json",
          async:false,
          success:function(r){
            console.log(r)
            options = '';
            if (!r.length) {
              alert("No existen profesores para esa asignatura");
            };
            for (var i = 0; i < r.length; i++) {
              options+= "<option value='"+r[i].profesor_id+"'>"+r[i].apellidos+"-"+r[i].nombres+"</option>";
            };
            $("#alumnoasignatura_profesor_id").html(options);
            $("#cargando").css("display","none");
            //console.log(r);
          }
        })
      })
  })

</script>