<?php echo Tag::css("mios"); ?>

<div class="alert bg-info">
	<div class="pull-left">
		<?php echo Html::img("evaluacion.png","icono de evaluaciones","width='100px'") ?>
	</div>
	<div class="pull-left" >
		<h2 class="titulo_de_imagen"><?php echo $titulo ?></h2>
	</div>
	<div class="clearfix"></div>
	
	<div class="clearfix"></div>
	<br>
	<div class="pull-right">

<!-- Button trigger modal -->
		<?php echo Html::link("#","<span class=\"glyphicon glyphicon-plus\" aria-hidden=\"true\"></span>  Ingresar nueva Inscripcion","class='btn btn-default btn-sm' data-toggle=\"modal\" data-target=\".bs-example-modal-lg\"") ?>
	</div>
	<div class="clearfix"></div>

</div>

<?php View::content() ?>

<table class="table datatable">
  
    <thead>
      <th>Semestre</th>
      <th>Sección</th>
      <th>Código</th>
      <th>Asignatura</th>
      <th>Prof.</th>
      <th>Alumno</th>
      <th>Fecha Inscripción</th>
    </thead>
  <?php foreach ($incripcionalumnoasignatura as $key => $value): ?>
    <tr>
      <td><?php echo $value->numero ?></td>
      <td><?php echo $value->seccion ?></td>
      <td><?php echo $value->asignatura_codigo ?></td>
      <td><?php echo $value->asignatura ?></td>
      <td><?php echo ucfirst($value->apellidos)." ".ucfirst($value->nombres) ?></td>
      <td><?php echo ucfirst($value->apellidos_alumnos)." ".ucfirst($value->nombres_alumno) ?></td>
      <td><?php echo $value->creado ?></td>
    </tr>
  <?php endforeach ?>
</table>


<!-- Modal -->
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
  	<?php echo Form::open("evaluacion/inscripcion","POST","id='form_inscripcion'") ?>
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Formulario de inscripción</h4>
      </div>
      <div class="modal-body">
      	
      	<div class="row">
      		
      		<div class="col-md-8">
          <label for="">Elegir el Curso</label>
      			<table class="table datatable">
                 <thead>
                   <th>Semes.</th>
                   <th>Sección</th>
                   <th>Cod</th>
                   <th>Asig.</th>
                   <th>Prof.</th>
                   <th></th>
                 </thead>
                 <?php foreach ($profesorasignatura as $key => $value): ?>
                   <tr>
                     <td><?php echo $value->numero ?></td>
                     <td><?php echo $value->seccion ?></td>
                     <td><?php echo $value->asignatura_codigo ?></td>
                     <td><?php echo $value->asignatura ?></td>
                     <td><?php echo ucfirst($value->nombres)." ".ucfirst($value->apellidos) ?></td>
                     <td><?php echo Form::radio("incripcionalumnoasignatura.profesorasignatura_id",$value->profesorasignatura_id,"class='radio'") ?></td>
                   </tr>
                 <?php endforeach ?>
            </table>
      		</div>
      		<div class="col-md-4">
          <label for="">Elegir el alumno</label>
      			<?php echo Form::dbselect("incripcionalumnoasignatura.alumno_id","alum",array("alumno","getAlumnos"),"Alumno","class='form-control' required") ?>
      		</div>
      	</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary">Guardar</button>
      </div>
    </div>
    <?php echo Form::close() ?>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    var checked = 0;
    $("#form_inscripcion").submit(function(e){
    
      $(".radio").each(function(){
        if($(this).is(":checked")){
          checked=1;
        }
      })
      if (!checked) {
        e.preventDefault();
        alert("Se tiene que seleccionar un curso")
        return false;
      };
    })
  })
</script>