<!DOCTYPE html>
<html lang="es">
<head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><?php echo $titulo ?></title>
  <?php Tag::css('bienvenida') ?>
  <?php Tag::css('style') ?>
  <?php Tag::css('bootstrap/css/bootstrap.min') ?>
  <?php Tag::css('bootstrap/datepicker/css/bootstrap-datepicker.min') ?>
 
  <?php Tag::css('datatable/css/dataTables.bootstrap.min') ?>

  <?php echo Html::includeCss() ?>
  <!-- js -->
  <?php echo Tag::js("jquery/jquery-1.11.3.min") ?>
  <?php echo Tag::js("bootstrap/datepicker/js/bootstrap-datepicker") ?>
  <?php echo Tag::js("bootstrap/js/bootstrap.min") ?>
  <?php echo Tag::js("bootstrap/datepicker/locales/bootstrap-datepicker.es.min") ?>
  <?php echo Tag::js("datatable/js/jquery.dataTables.min") ?>
  <?php echo Tag::js("datatable/js/dataTables.bootstrap.min") ?>
</head>
<body>
  <div class="container">
    <h2 id='info-app'>Sistema de Notas</h2>
  </div>
  <div id='content'>


    <div id='info'>
      <?php View::content(); ?>

    </div>

  </div>
  <script type="text/javascript">
    $(document).ready(function(){
      $('.datepicker').datepicker({
          format: 'yyyy/mm/dd',
          language: 'es'
      })
      $('.datatable').DataTable({
        language:{
            "sProcessing":     "Procesando...",
            "sLengthMenu":     "Mostrar _MENU_ registros",
            "sZeroRecords":    "No se encontraron resultados",
            "sEmptyTable":     "Ningún dato disponible en esta tabla",
            "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
            "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
            "sInfoPostFix":    "",
            "sSearch":         "Buscar:",
            "sUrl":            "",
            "sInfoThousands":  ",",
            "sLoadingRecords": "Cargando...",
            "oPaginate": {
                "sFirst":    "Primero",
                "sLast":     "Último",
                "sNext":     "Siguiente",
                "sPrevious": "Anterior"
            },
            "oAria": {
                "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                "sSortDescending": ": Activar para ordenar la columna de manera descendente"
            }
        }
      });
    })
  </script>
</body>
</html>
