  	<?php echo Form::open("","POST") ?>
 
        <h4 class="modal-title" id="myModalLabel">Editar de alumno</h4>

      	<div class="row">
      		<div class="col-md-6">
      			<div class="form-group">
		      		<label>DNI Nº</label>
		      		<?php echo Form::hidden("alumno.id") ?>
		      		<?php echo Form::text("alumno.dni","class='form-control' maxlength=\"8\" ") ?>
		      	</div>
		      	<div class="form-group">
		      		<label>Nombres</label>
		      		<?php echo Form::text("alumno.nombres","class='form-control' maxlength=\"50\" ") ?>
		      	</div>
		      	
		      	<div class="form-group">
		      		<label>Direccion</label>
		      		<?php echo Form::text("alumno.direccion","class='form-control' maxlength=\"50\" ") ?>
		      	</div>
		      	<div class="form-group">
		      		<label>Semestre</label>
		      		<?php echo Form::dbselect("alumno.semestre_id",null,null,"Seleccione","class='form-control' title='Al cambiar el semestre se cambian las secciones'") ?>
		      	</div>
      		</div>
  			<div class="col-md-6">
		      	
		      	<div class="form-group">
		      		<label>Estado</label>
		      		<?php echo Form::select("alumno.estado",array("1"=>"Activo","0"=>"No Activo"),"class='form-control'") ?>
		      	</div>
		      	<div class="form-group">
		      		<label>Apellidos</label>
		      		<?php echo Form::text("alumno.apellidos","class='form-control' maxlength=\"50\" ") ?>
		      	</div>

		      	<div class="form-group">
		      		<label>Celular</label>
		      		<?php echo Form::text("alumno.celular","class='form-control' maxlength=\"25\" ") ?>
		      	</div>
		      	<div class="form-group">
		      		<label>Sección</label>
		      		<div id="cargando_secciones" style="display:none">Cargando Secciones...</div>
		      		<?php echo Form::dbselect("alumno.seccion_id","seccion",null,"Seleccione","class='form-control'") ?>
		      	</div>
  			</div>
	      	
      	</div>
        <?php echo Html::link("alumno/","Lista de Alumnos","class=\"btn btn-default\" ") ?>
        <button type="submit" class="btn btn-primary">Actualizar Registro</button>

    </div>
    <?php echo Form::close() ?>

    <script type="text/javascript">
	$(document).ready(function(){
		$("#alumno_semestre_id").on("change",function(){
			var id = $(this).val();
			$("#cargando_secciones").css("display","block");
			$.ajax({
				url:"../../seccion/obtener_secciones_por_semestre/?id="+id,
				type:"get",
				dataType:"json",
				async:false,
				success:function(r){
					options = '';
					for (var i = 0; i < r.length; i++) {
						options+= "<option value='"+r[i].id+"'>"+r[i].seccion+"</option>";
					};
					$("#alumno_seccion_id").html(options);
					$("#cargando_secciones").css("display","none");
					//console.log(r);
				}

			})
		})
	})
</script>