  	<?php echo Form::open("","POST") ?>
 
        <h4 class="modal-title" id="myModalLabel">Editar de alumno</h4>

      	<div class="row">
      		<div class="col-md-6">
      			<div class="form-group">
		      		<label>DNI Nº</label>
		      		<?php echo Form::hidden("alumno.id") ?>
		      		<?php echo Form::text("alumno.dni","class='form-control' maxlength=\"8\" ") ?>
		      	</div>
		      	<div class="form-group">
		      		<label>Nombres</label>
		      		<?php echo Form::text("alumno.nombres","class='form-control' maxlength=\"50\" ") ?>
		      	</div>
		      	
		      	<div class="form-group">
		      		<label>Direccion</label>
		      		<?php echo Form::text("alumno.direccion","class='form-control' maxlength=\"50\" ") ?>
		      	</div>
      		</div>
  			<div class="col-md-6">
		      	
		      	<div class="form-group">
		      		<label>Estado</label>
		      		<?php echo Form::select("alumno.estado",array("1"=>"Activo","0"=>"No Activo"),"class='form-control'") ?>
		      	</div>
		      	<div class="form-group">
		      		<label>Apellidos</label>
		      		<?php echo Form::text("alumno.apellidos","class='form-control' maxlength=\"50\" ") ?>
		      	</div>

		      	<div class="form-group">
		      		<label>Celular</label>
		      		<?php echo Form::text("alumno.celular","class='form-control' maxlength=\"25\" ") ?>
		      	</div>
  			</div>
	      	
      	</div>
        <?php echo Html::link("alumno/","Lista de Alumnos","class=\"btn btn-default\" ") ?>
        <button type="submit" class="btn btn-primary">Actualizar Registro</button>

    </div>
    <?php echo Form::close() ?>