<?php echo Form::open("","POST") ?>
   
        <h4 class="modal-title" id="myModalLabel">Editar Profesor</h4>
     	<?php echo Form::hidden("profesor.id") ?>
      	<div class="row">
      		<div class="col-md-5">
      			<div class="form-group">
		      		<label>DNI Nº</label>
		      		<?php echo Form::text("profesor.dni","class='form-control' maxlength=\"8\" ") ?>
		      	</div>
		      	<div class="form-group">
		      		<label>Nombres</label>
		      		<?php echo Form::text("profesor.nombres","class='form-control' maxlength=\"50\" ") ?>
		      	</div>
		      	<div class="form-group">
		      		<label>Apellidos</label>
		      		<?php echo Form::text("profesor.apellidos","class='form-control' maxlength=\"50\" ") ?>
		      	</div>
		      	<div class="form-group">
		      		<label>Especialidad</label>
		      		<?php echo Form::text("profesor.especialidad","class='form-control' maxlength=\"50\" ") ?>
		      	</div>
		      	<div class="form-group">
		      		<label>Correo</label>
		      		<?php echo Form::email("profesor.correo","class='form-control' maxlength=\"50\" ") ?>
		      	</div>
      		</div>
  			<div class="col-md-7">
  				<div class="form-group">
		      		<label>Dirección</label>
		      		<?php echo Form::text("profesor.direccion","class='form-control'") ?>
		      	</div>
		      	<div class="form-group">
		      		<label>Celular</label>
		      		<?php echo Form::text("profesor.celular","class='form-control' maxlength=\"18\" ") ?>
		      	</div>
		      	
		      	<div class="form-group">
    
		      		<label>Fecha de Nacimiento</label>
		      		<div class="input-group date">
			      		<?php echo Form::text("profesor.fnacimiento","class='form-control datepicker'") ?>
			      		<div class="input-group-addon"><span class="glyphicon glyphicon-th" aria-hidden="true"></span></div>
		      		</div>
		      	</div>
		      	<div class="form-group">
		      		<label>Estado</label>
		      		<?php echo Form::select("profesor.estado",array("1"=>"Activo","0"=>"No Activo"),"class='form-control'") ?>
		      	</div>
		      	<div class="form-group">
		      		<label>Tipo de Usuario</label>
		      		<?php echo Form::select("profesor.tipo_usuario",array("1"=>"Docente","0"=>"Administrador"),"class='form-control'") ?>
		      	</div>
  			</div>
	      	
      	</div>
 

        <?php echo Html::link("profesor/","Lista de Profesores","class=\"btn btn-default\" ") ?>
        <button type="submit" class="btn btn-primary">Actualizar Registro</button>

    <?php echo Form::close() ?>