<?php echo Form::open("asignatura/nueva","POST") ?>
 
        <h4 class="modal-title" id="myModalLabel">Editar asignatura</h4>

      	<div class="row">
      		<div class="col-md-6">
      			<div class="form-group">
		      		<label>Código</label>
		      		<?php echo Form::hidden("asignatura.id") ?>
		      		<?php echo Form::text("asignatura.codigo","class='form-control' maxlength=\"8\" ") ?>
		      	</div>
		      	<div class="form-group">
		      		<label>Asignatura</label>
		      		<?php echo Form::text("asignatura.asignatura","class='form-control' maxlength=\"50\" ") ?>
		      	</div>
		      	<div class="form-group">
		      		<label>Semestre</label>
		      		<?php echo Form::dbselect("asignatura.semestre_id",NULL,NULL,"Seleccione","class='form-control' required") ?>
		      	</div>
		      	<div class="form-group">
		      		<label>HT</label>
		      		<?php echo Form::number("asignatura.ht","class='form-control' maxlength=\"2\" max=\"100\" maxlength = \"3\"  oninput=\"maxLengthCheck(this)\"") ?>
		      	</div>
		      	
      		</div>
  			<div class="col-md-6">
  			<div class="form-group">
		      		<label>HP</label>
		      		<?php echo Form::number("asignatura.hp","class='form-control' maxlength=\"2\" max=\"100\" maxlength = \"3\"  oninput=\"maxLengthCheck(this)\"") ?>
		      	</div>
  				<div class="form-group">
		      		<label>TH</label>
		      		<?php echo Form::number("asignatura.th","class='form-control' maxlength=\"2\" max=\"100\" maxlength = \"3\" oninput=\"maxLengthCheck(this)\"") ?>
		      	</div>
		      	<div class="form-group">
		      		<label>CR</label>
		      		<?php echo Form::number("asignatura.cr","class='form-control' maxlength=\"2\" max=\"100\" maxlength = \"3\" oninput=\"maxLengthCheck(this)\"") ?>
		      	</div>
		      	
		      
		      	<div class="form-group">
		      		<label>Estado</label>
		      		<?php echo Form::select("asignatura.estado",array("1"=>"Activo","0"=>"No Activo"),"class='form-control' required") ?>
		      	</div>
  			</div>
	      	
      	</div>

        <?php echo Html::link("profesor/","Lista de Asignaturas","class=\"btn btn-default\" ") ?>
        <button type="submit" class="btn btn-primary">Actualizar Registro</button>

    </div>
    <?php echo Form::close() ?>